# Generated by Django 4.1.2 on 2022-11-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_element', models.CharField(default='', max_length=100, verbose_name='Название товара')),
                ('description_element', models.TextField(default='', max_length=250, verbose_name='Описание товара')),
                ('id_element', models.IntegerField(max_length=10, verbose_name='Уникальный id,не должен повторяться')),
            ],
        ),
    ]
